---
title: "R Notebook"
output: html_notebook
---


```{r}
library(dplyr)
library(ggplot2)
library('corrplot')
library('RColorBrewer')
library(stringr)#para extraer los titulos relevantes de names
library(zoo)#la utilizo para la funcion na.approx() para interpolar los valores faltantes NA de la columna AGE
library(caTools)#la utilizo para la funcion sample.split dividir el cojunto de datos en entrenamiento y prueba
library(caret)#la utilizo para dividir el conjunto de datos
library(e1071)
library(mice)# La librería mice permite realizar la imputacion de los datos mediante diferentes técnicas.Multivariate Imputations by Chained Equations (MICE).
```

```{r}
#importo el conjunto de datos
titanic_data <- read.csv("data_titanic_proyecto.csv")
titanic_data
```

```{r}
summary(titanic_data)
```

```{r}
colSums(is.na(titanic_data))
```

```{r}
imputed_data <- mice(titanic_data%>%select(Age,PassengerId), method = "norm.boot")


```

```{r}
Data_Impu_boot <- mice::complete(imputed_data)

par(mfrow=c(1,2))

plot(density(titanic_data$Age ,na.rm = T),col=2,main="Edad")
lines(density(Data_Impu_boot$Age ),col=3)

plot(density(titanic_data$PassengerId,na.rm = T),col=2,main="PassengerId")
lines(density(Data_Impu_boot$PassengerId),col=3)

```

```{r}
imputed_data <- mice(titanic_data%>%select(Age,PassengerId), method = "mean")


```

```{r}
Data_Impu_media <- mice::complete(imputed_data)

par(mfrow=c(1,2))

plot(density(titanic_data$Age ,na.rm = T),col=2,main="Edad")
lines(density(Data_Impu_media$Age ),col=3)

plot(density(titanic_data$PassengerId,na.rm = T),col=2,main="PassengerId")
lines(density(Data_Impu_media$PassengerId),col=3)

```


```{r}
#x2<-titanic_data$Age
#titanic_data$Age[is.na(titanic_data$Age)] <- mean(titanic_data$Age, na.rm = TRUE)
titanic_data<-titanic_data%>%mutate(Age = Data_Impu_boot$Age, PassengerId = Data_Impu_boot$PassengerId)
titanic_data
```

```{r}
colSums(is.na(titanic_data))
```

```{r}
#limpiar y transformar los datos
titanic_data$Embarked <- as.factor(titanic_data$Embarked)#transformar columna embarked en un factor(variable categorica)
titanic_data$passenger_class <- as.factor(titanic_data$passenger_class)
#titanic_data$passenger_sex <- as.factor(titanic_data$passenger_sex)
titanic_data$passenger_survived <- as.integer(titanic_data$passenger_survived == "Y") #comparo cada valor de la columna passenger_survived con "Y" TRUE si valor es igual a "Y" y FALSE "N" con as.integer TRUE pasa a 1 y FALSE pasa a 0
titanic_data$passenger_sex <- as.integer(titanic_data$passenger_sex == "M") #comparo cada valor de la columna passenger_sex con "Y" TRUE si valor es igual a "Y" y FALSE "N" con as.integer TRUE pasa a 1 y FALSE pasa a 0
```

```{r}
#extraer los titulos de la columna Name y crear una nueva columna Titulos
titanic_data$Titulos <- str_extract(titanic_data$Name, "(Mrs|Mr|Miss|Master|Don|Dr|Rev|Mme|Ms|Major|Lady|Sir|Mlle|Col|Capt|the Countess)\\.")

#reemplazar valores NA (no coincidentes) con Otro
titanic_data$Titulos[is.na(titanic_data$Titulos)] <- "Otro"

#verificar los cambios realizados
head(titanic_data)
```


```{r}
str(titanic_data)#con esto muestro la estructura interna del data frame
```

```{r}
# creo un conjunto de datos sin columnas innecesarias
titanic_data_clean <- titanic_data %>% select(-Name, -Ticket, -Cabin)
titanic_data_clean
```

```{r}
#contar la cantidad de valores NA en la columna Age por cada titulo
na_count_by_title <- aggregate(Age ~ Titulos, titanic_data_clean, FUN = function(x) sum(is.na(x)))

#contar cuantos titulos tienen al menos un valor NA en la columna Age
titles_with_na <- sum(na_count_by_title$Age > 0)

#imprimiendo el resultado
print(titles_with_na)

```


```{r}
#creo variables dummy(convertir variables categoricas en variables numericas binarias ) para las variables categoricas
titanic_data_clean <- titanic_data_clean %>%
   mutate( #passenger_clas_i = as.integer(passenger_class ))
  
#  mutate(Male = as.integer(passenger_sex == "M"),
#         Female = as.integer(passenger_sex == "F"),
  
#         AGE = as.integer(titanic_data_clean$Age),
#         Class_Upper = as.integer(passenger_class == "Upper"),
#         Class_Middle = as.integer(passenger_class == "Middle"),
#         Class_Lower = as.integer(passenger_class == "Lower"),
#         Embarked_S = as.integer(Embarked == "S"),
#         Embarked_C = as.integer(Embarked == "C"),
#         Embarked_Q = as.integer(Embarked == "Q"),
          Fare = as.integer(Fare)
         )
titanic_data_clean

```

```{r}
#identificar el titulo que tiene valores NA en la columna AGE
na_titles <- unique(titanic_data_clean$Titulos[is.na(titanic_data_clean$AGE)])


for (title in na_titles) {
  average_age <- mean(titanic_data_clean$AGE[titanic_data_clean$Titulos == title & !is.na(titanic_data_clean$AGE)], na.rm = TRUE)
  titanic_data_clean$AGE[titanic_data_clean$Titulos == title & is.na(titanic_data_clean$AGE)] <- average_age
}

# Verificar que no haya valores faltantes en la columna AGE
summary(titanic_data_clean$AGE)
titanic_data_clean
```


```{r}
#calcular la mediana de la edad para cada titulo
#mediana_edad_por_titulo <- titanic_data_clean %>%
 # group_by(Titulos) %>%
  #summarise(Mediana_Edad = median(AGE, na.rm = TRUE))

#unir la mediana de la edad por titulo al dataset original
#titanic_data_clean <- left_join(titanic_data_clean, mediana_edad_por_titulo, by = "Titulos")

#imputar los valores faltantes de la columna Age utilizando la mediana de la edad segun el titulo
#titanic_data_clean$AGE <- ifelse(is.na(titanic_data_clean$AGE), titanic_data_clean$Mediana_Edad, titanic_data_clean$AGE)

#eliminar la columna Mediana_Edad ya que no es necesaria
#titanic_data_clean <- titanic_data_clean %>%
 # select(-Mediana_Edad)

#verificar que no haya valores faltantes en la columna AGE
#summary(titanic_data_clean$AGE)
#titanic_data_clean
```


```{r}
#definir una funcion para categorizar la edad
#categorize_age <- function(age) {
#  if (is.na(age)) {
#    return(NA)
#  } else if (age <= 2) {
#    return("Infant")
#  } else if (age <= 12) {
#    return("Child")
#  } else if (age <= 19) {
#    return("Teenager")
#  } else if (age <= 35) {
#    return("Young Adult")
#  } else if (age <= 65) {
#    return("Adult")
#  } else {
#    return("Senior")
#  }
#}

#aplicar la funcion para categorizar la columna Age
#titanic_data_clean <- titanic_data_clean %>%
#  mutate(AgeCategory = sapply(AGE, categorize_age))

#convertir la nueva columna AgeCategory en un factor
#titanic_data_clean$AgeCategory <- as.factor(titanic_data_clean$AgeCategory)
#titanic_data_clean

#mostrar un resumen de la nueva columna AgeCategory
#summary(titanic_data_clean$AgeCategory)

```

```{r}

#titanic_data_clean$AgeCategory <- factor(titanic_data_clean$AgeCategory, levels = c("Infant", "Child", "Teenager", "Young Adult", "Adult", "Senior"))

#convertir la columna AgeCategory en una columna numerica
#titanic_data_clean$NumericAgeCategory <- as.integer(titanic_data_clean$AgeCategory)

#mostrar un resumen de la nueva columna NumericAgeCategory
#summary(titanic_data_clean$NumericAgeCategory)
#titanic_data_clean

```

```{r}
# eliminar las variables originales categoricas
#titanic_data_clean <- titanic_data_clean %>%
#  select(-passenger_sex, -passenger_class, -Embarked,-AgeCategory,-Age,-Fare,-Female,-Class_Lower)
#titanic_data_clean
```

```{r}
#aca aplico la interpolación lineal a la columna AGE
#titanic_data_clean$AGE <- na.approx(titanic_data_clean$AGE, na.rm = FALSE)

#redondeo la columna Age a 0 decimales
#titanic_data_clean$AGE <- round(titanic_data_clean$AGE, 0)

#titanic_data_clean
```
```{r}
#titanic_data_clean$AGE <- as.integer(round(titanic_data_clean$AGE))

#mostrando un resumen de la columna AGE
#summary(titanic_data_clean$AGE)
#titanic_data_clean
```

```{r}
#contando la cantidad de cada titulo de la columna Titulos
titulo_recuento <- table(titanic_data_clean$Titulos)

#imprimimiendo el recuento de cada titulo
print(titulo_recuento)
```



```{r}
#convertir los titulos en factores
#obtener los niveles únicos de los titulos
titulos_unicos <- unique(titanic_data_clean$Titulos)

#convertir los titulos en factores utilizando los niveles unicos
titanic_data_clean$Titulos <- factor(titanic_data_clean$Titulos, levels = titulos_unicos)

#convertir los factores en numeros enteros
titanic_data_clean$Titulos <- as.integer(titanic_data_clean$Titulos)

#mostrar un resumen de la columna Titulos
summary(titanic_data_clean$Titulos)
titanic_data_clean
```

```{r}
#convertir los titulos en factores
#obtener los niveles únicos de los titulos
pasajeros_unicos <- unique(titanic_data_clean$passenger_class)

#convertir los titulos en factores utilizando los niveles unicos
titanic_data_clean$passenger_class <- factor(titanic_data_clean$passenger_class, levels = pasajeros_unicos)

#convertir los factores en numeros enteros
titanic_data_clean$passenger_class <- as.integer(titanic_data_clean$passenger_class)

#mostrar un resumen de la columna Titulos
summary(titanic_data_clean$passenger_class)
titanic_data_clean
```


```{r}
#convertir los titulos en factores
#obtener los niveles únicos de los titulos
embarques_unicos <- unique(titanic_data_clean$Embarked)

#convertir los titulos en factores utilizando los niveles unicos
titanic_data_clean$Embarked <- factor(titanic_data_clean$Embarked, levels = embarques_unicos)

#convertir los factores en numeros enteros
titanic_data_clean$Embarked <- as.integer(titanic_data_clean$Embarked)

#mostrar un resumen de la columna Titulos
summary(titanic_data_clean$Embarked)
titanic_data_clean
```



```{r}
#titanic_data_clean <- titanic_data_clean %>%
#   select(-passenger_class)
# titanic_data_clean
```

```{r}
#
#Se grafica el histogra de Fare para ver como es la distribucion de la varaible Age 
    
     hist(x = titanic_data_clean$Age, main = "Histograma de AGE", 
     xlab = "Age", ylab = "Frecuencia",
     col = "ivory")
#como se puede apreciar esta variable tiene mucho sesgo a la derecha
```




```{r}

#Se grafica el histogra de Fare para ver como es la distribucion de la varaible Fare 
    
#     hist(x = log(titanic_data_clean$Fare_i+2), main = "Histograma de Precio ticket", 
#     xlab = "FARE", ylab = "Frecuencia",
#     col = "ivory")
# aplicando logaritmos naturales a los datos de la varaible se ve que mejora la distribucion

```
```{r}

#Se grafica el histogra de Fare para ver como es la distribucion de la varaible AGE 
    
#     hist(x = log(titanic_data_clean$AGE), main = "Histograma de edades ", 
#     xlab = "AGE", ylab = "Frecuencia",
#     col = "ivory")
# aplicando logaritmos naturales a los datos de la varaible se ve que mejora la distribucion

```

```{r}

#se tranforman los datos aplicando logaritmo
log_1 <- log(titanic_data_clean$Fare+2)#
titanic_data_clean$Fare_log <- log_1

#log_1 <- log(titanic_data_clean$AGE+2)#
#titanic_data_clean$AGE_log <- log_1


titanic_data_clean

```

```{r}
titanic_data_clean <- titanic_data_clean %>%
   select(-Fare)
 titanic_data_clean
```





```{r}

#Se grafica el histogra de Fare para ver como es la distribucion de la varaible AGE
    
#     hist(x = log(titanic_data_clean$AGE_log), main = "Histograma edades", 
#     xlab = "AGE", ylab = "Frecuencia",
#     col = "ivory")
# aplicando logaritmos naturales a los datos de la varaible se ve que mejora la distribucion

```

```{r}
# dividir los datos en conjuntos de entrenamiento y prueba (60% - 40%)
set.seed(1234) #establece una semilla para que la division sea reproducible

sample <- sample.split(titanic_data_clean$Titulos, SplitRatio = 0.9)
train_data  <- subset(titanic_data_clean, sample == TRUE)
validation_data   <- subset(titanic_data_clean, sample == FALSE)

#se muestra las dimensiones del conjunto de entrenamiento

dim(train_data)

#se muestra las dimensiones del conjunto de prueba
dim(validation_data)

```

```{r}
train_data %>% 
  group_by(passenger_survived) %>% 
  summarise(numero_casos=n())
```

```{r}
validation_data %>% 
  group_by(passenger_survived) %>% 
  summarise(numero_casos=n())
```


```{r}
PassengerId_t <- train_data$PassengerId

train_data_c <- preProcess(train_data, method = c("range")) 
train_data_c 


```


```{r}
transformed <- predict(train_data_c, newdata = train_data)
train_data <- transformed
train_data
```



```{r}

validation_data_c <- preProcess(validation_data, method = c("range")) 

```


```{r}
transformed <- predict(validation_data_c, newdata = validation_data)
validation_data <- transformed
validation_data
```



```{r}
bin_model1 <- 
  glm(passenger_survived ~ Age +  Fare_log + passenger_sex, 
      data = train_data, 
      family = binomial)
summary(bin_model1)

```

```{r}
bin_model2 <- 
  glm(passenger_survived ~Age + SibSp + Fare_log + passenger_sex + passenger_class , 
      data = train_data, 
      family = binomial)
summary(bin_model2)

```

```{r}
mod.all <- glm(passenger_survived ~ ., data=train_data, family="binomial")
model <- stats::step(mod.all, trace=FALSE, direction="backward")
summary(model)

```



```{r}

# entrenando el modelo de regresión logistica con el conjunto de entrenamiento
#model <- glm(passenger_survived ~ ., data = train_data , family = "binomial")
#ctrlspecs <- trainControl(method = "cv", number = 10, savePredictions = "all", classProbs = TRUE)
#ctrlspecs <- trainControl(method = "cv", number = 10)
#model <- train(passenger_survived ~., data = train_data, method = "glm", family= binomial, trControl = ctrlspecs)

#summary(model)
```



```{r}
#predecir la supervivencia utilizando el modelo entrenado en el conjunto de validacion
#predictions <- predict(model, newdata = validation_data, type = "response")
predictions <- predict(model, newdata = validation_data,type = "response")

predicted_survived <- ifelse(predictions > 0.5, "Y", "N")


#calcular la precision del modelo en el conjunto de validacion
accuracy <- sum(predicted_survived == validation_data$passenger_survived) / length(validation_data$passenger_survived)
accuracy

```

```{r}
#funciones para calcular precision, recall y F1 score
precision <- function(matrix) {
	# True positive
    tp <- matrix[2, 2]
	# false positive
    fp <- matrix[1, 2]
    return (tp / (tp + fp))
}

recall <- function(matrix) {
# true positive
    tp <- matrix[2, 2]# false positive
    fn <- matrix[2, 1]
    return (tp / (tp + fn))
}
#creando una matriz de confusion
conf_matrix <- table(predicted_survived, validation_data$passenger_survived)

prec <- precision(conf_matrix)
prec
rec <- recall(conf_matrix)
rec
```

```{r}
f1 <- 2 * ((prec * rec) / (prec + rec))
f1
```
#AQUI TERMINA EL ENTRENAMIENTO DEL MODELO DE REGRESION LOGISTICA BINOMIAL 

```{r}
#importo el conjunto de datos
evaluation_data <- read.csv("evaluation_dataset.csv")
evaluation_data
```

```{r}
summary(evaluation_data)
```

```{r}
#limpiar y transformar los datos
evaluation_data$Embarked <- as.factor(evaluation_data$Embarked)#transformar columna embarked en un factor(variable categorica)
evaluation_data$passenger_class <- as.factor(evaluation_data$passenger_class)
#evaluation_data$passenger_sex <- as.factor(evaluation_data$passenger_sex)
evaluation_data$passenger_sex <- as.integer(evaluation_data$passenger_sex == "M") #comparo cada valor de la columna passenger_sex con "Y" TRUE si valor es igual a "Y" y FALSE "N" con as.integer TRUE pasa a 1 y FALSE pasa a 0

```

```{r}
#extraer los titulos de la columna Name y crear una nueva columna Titulos
evaluation_data$Titulos <- str_extract(evaluation_data$Name, "(Mrs|Mr|Miss|Master|Don|Dr|Rev|Mme|Ms|Major|Lady|Sir|Mlle|Col|Capt|the Countess|Jonkheer)\\.")

#reemplazar valores NA (no coincidentes) con Otro
evaluation_data$Titulos[is.na(evaluation_data$Titulos)] <- "Otro"

#verificar los cambios realizados
head(evaluation_data)
```

```{r}
str(evaluation_data)#con esto muestro la estructura interna del data frame

```



```{r}
colSums(is.na(evaluation_data))
```

```{r}
imputed_data <- mice(evaluation_data%>%select(Age,PassengerId), method = "norm.boot")


```


```{r}
Data_Impu_boot <- mice::complete(imputed_data)

par(mfrow=c(1,2))

plot(density(evaluation_data$Age ,na.rm = T),col=2,main="Edad")
lines(density(Data_Impu_boot$Age ),col=3)

plot(density(evaluation_data$PassengerId,na.rm = T),col=2,main="PassengerId")
lines(density(Data_Impu_boot$PassengerId),col=3)

```


```{r}

#evaluation_data$Age[is.na(evaluation_data$Age)] <- mean(evaluation_data$Age, na.rm = TRUE)
evaluation_data<-evaluation_data%>%mutate(Age = Data_Impu_boot$Age, PassengerId = Data_Impu_boot$PassengerId)
evaluation_data

```

```{r}
colSums(is.na(evaluation_data))
```


```{r}
# creo un conjunto de datos sin columnas innecesarias
evaluation_data_clean <- evaluation_data %>% select(-Name, -Ticket, -Cabin)
evaluation_data_clean
```


```{r}
#contar la cantidad de valores NA en la columna Age por cada titulo
na_count_by_title <- aggregate(Age ~ Titulos, evaluation_data_clean, FUN = function(x) sum(is.na(x)))

#contar cuantos titulos tienen al menos un valor NA en la columna Age
titles_with_na <- sum(na_count_by_title$Age > 0)

#imprimiendo el resultado
print(titles_with_na)
```


```{r}
#creo variables dummy(convertir variables categoricas en variables numericas binarias ) para las variables categoricas
evaluation_data_clean <- evaluation_data_clean %>%
  mutate(#passenger_class_i = as.integer(passenger_class))
#         Female = as.integer(passenger_sex == "F"),
#         AGE = as.integer(evaluation_data_clean$Age),
#         Class_Upper = as.integer(passenger_class == "Upper"),
#         Class_Middle = as.integer(passenger_class == "Middle"),
#         Class_Lower = as.integer(passenger_class == "Lower"),
#         Embarked_S = as.integer(Embarked == "S"),
#         Embarked_C = as.integer(Embarked == "C"),
#         Embarked_Q = as.integer(Embarked == "Q"),
         Fare = as.integer(Fare)
         )
evaluation_data_clean
```


```{r}
#identificar el titulo que tiene valores NA en la columna AGE
na_titles <- unique(evaluation_data_clean$Titulos[is.na(evaluation_data_clean$AGE)])


for (title in na_titles) {
  average_age <- mean(evaluation_data_clean$AGE[evaluation_data_clean$Titulos == title & !is.na(evaluation_data_clean$AGE)], na.rm = TRUE)
  evaluation_data_clean$AGE[evaluation_data_clean$Titulos == title & is.na(evaluation_data_clean$AGE)] <- average_age
}

# Verificar que no haya valores faltantes en la columna AGE
summary(evaluation_data_clean$AGE)
evaluation_data_clean
```

```{r}
#definir una funcion para categorizar la edad
#categorize_age <- function(age) {
#  if (is.na(age)) {
#    return(NA)
#  } else if (age <= 2) {
#    return("Infant")
#  } else if (age <= 12) {
#    return("Child")
#  } else if (age <= 19) {
#    return("Teenager")
#  } else if (age <= 35) {
#    return("Young Adult")
#  } else if (age <= 65) {
#    return("Adult")
#  } else {
#    return("Senior")
#  }
#}

#aplicar la funcion para categorizar la columna Age
#evaluation_data_clean <- evaluation_data_clean %>%
#  mutate(AgeCategory = sapply(AGE, categorize_age))

#convertir la nueva columna AgeCategory en un factor
#evaluation_data_clean$AgeCategory <- as.factor(evaluation_data_clean$AgeCategory)
#evaluation_data_clean

#mostrar un resumen de la nueva columna AgeCategory
#summary(evaluation_data_clean$AgeCategory)
```

```{r}
#evaluation_data_clean$AgeCategory <- factor(evaluation_data_clean$AgeCategory, levels = c("Infant", "Child", "Teenager", "Young Adult", "Adult", "Senior"))

#convertir la columna AgeCategory en una columna numerica
#evaluation_data_clean$NumericAgeCategory <- as.integer(evaluation_data_clean$AgeCategory)

#mostrar un resumen de la nueva columna NumericAgeCategory
#summary(evaluation_data_clean$NumericAgeCategory)
#evaluation_data_clean
```

```{r}
# eliminar las variables originales categoricas
#evaluation_data_clean <- evaluation_data_clean %>%
#  select( -passenger_class)
#evaluation_data_clean
```


```{r}
#contando la cantidad de cada titulo de la columna Titulos
titulo_recuento <- table(evaluation_data_clean$Titulos)

#imprimimiendo el recuento de cada titulo
print(titulo_recuento)
```

```{r}
#convertir los titulos en factores
#obtener los niveles únicos de los titulos
titulos_unicos <- unique(evaluation_data_clean$Titulos)

#convertir los titulos en factores utilizando los niveles unicos
evaluation_data_clean$Titulos <- factor(evaluation_data_clean$Titulos, levels = titulos_unicos)

#convertir los factores en numeros enteros
evaluation_data_clean$Titulos <- as.integer(evaluation_data_clean$Titulos)

#mostrar un resumen de la columna Titulos
summary(evaluation_data_clean$Titulos)
evaluation_data_clean
```


```{r}
#convertir los titulos en factores
#obtener los niveles únicos de los titulos
embarques_unicos <- unique(evaluation_data_clean$Embarked)

#convertir los titulos en factores utilizando los niveles unicos
evaluation_data_clean$Embarked <- factor(evaluation_data_clean$Embarked, levels = embarques_unicos)

#convertir los factores en numeros enteros
evaluation_data_clean$Embarked <- as.integer(evaluation_data_clean$Embarked)

#mostrar un resumen de la columna Titulos
summary(evaluation_data_clean$Embarked)
evaluation_data_clean
```

```{r}
#convertir los titulos en factores
#obtener los niveles únicos de los titulos
pasasjeros_unicos <- unique(evaluation_data_clean$passenger_class)

#convertir los titulos en factores utilizando los niveles unicos
evaluation_data_clean$passenger_class <- factor(evaluation_data_clean$passenger_class, levels = pasasjeros_unicos)

#convertir los factores en numeros enteros
evaluation_data_clean$passenger_class <- as.integer(evaluation_data_clean$passenger_class)

#mostrar un resumen de la columna Titulos
summary(evaluation_data_clean$passenger_class)
evaluation_data_clean
```




```{r}
#
#Se grafica el histogra de Fare para ver como es la distribucion de la varaible Fare 
    
#     hist(x = evaluation_data_clean$Fare_i, main = "Histograma de Precio ticket", 
#     xlab = "FARE", ylab = "Frecuencia",
#     col = "ivory")
#como se puede apreciar esta variable tiene mucho sesgo a la derecha
```

```{r}
#Se grafica el histogra de Fare para ver como es la distribucion de la varaible Fare 
    
#     hist(x = log(evaluation_data_clean$Fare_i+2), main = "Histograma de Precio ticket", 
#     xlab = "FARE", ylab = "Frecuencia",
#     col = "ivory")
# aplicando logaritmos naturales a los datos de la varaible se ve que mejora la distribucion
```


```{r}
#se tranforman los datos aplicando logaritmo
log <- log(evaluation_data_clean$Fare+2)#
evaluation_data_clean$Fare_log <- log

#log <- log(evaluation_data_clean$AGE+2)#
#evaluation_data_clean$AGE_log <- log


evaluation_data_clean
```

```{r}
evaluation_data_clean <- evaluation_data_clean %>%
   select(-Fare)
 evaluation_data_clean
```


```{r}
PassengerId <- evaluation_data_clean$PassengerId

evaluation_data_clean_c <- preProcess(evaluation_data_clean, method = c("range")) 

```


```{r}
transformed <- predict(evaluation_data_clean_c, newdata = evaluation_data_clean)
evaluation_data_clean <- transformed
evaluation_data_clean
```


```{r}
titanic <- rbind(train_data,validation_data)# se hace un solo dataset
titanic
```


```{r}
# entrenando el modelo de regresión logistica con el conjunto de entrenamiento
model_test <- glm(model, data = titanic, family = "binomial")

#ctrlspecs <- trainControl(method = "cv", number = 10)
#model_test <- train(passenger_survived ~., data = titanic, method = "glm", family= binomial, trControl = ctrlspecs)

summary(model_test)
```



```{r}
#predecir la supervivencia utilizando el modelo entrenado en el conjunto de validacion
predictions <- predict(model_test, newdata = evaluation_data_clean, type = "response")
#predictions <- predict(model, newdata = evaluation_data_clean)
predicted_survived_test <- ifelse(predictions > 0.5, "Y", "N")
predicted_survived_test

```

```{r}
#se convierten los valores predecidos a valores de 0=N, 1=Y
passenger_survived <- as.integer(predicted_survived_test== "Y") #comparo cada valor de la columna passenger_survived con "Y" TRUE si valor es igual a "Y" y FALSE "N" con as.integer TRUE pasa a 1 y FALSE pasa a 0
passenger_survived
```

```{r}
#PassengerId <- evaluation_data_clean$PassengerId
predicciones_data <- cbind(PassengerId , passenger_survived ) 
predicciones_data

```

```{r}

#en la variable predicciones_data estas las predicciones utilizo sep = "," para especificar un separador personalizado 
write.csv(predicciones_data, "predictions16.csv", sep = ",", row.names = FALSE)


```

