---
title: "R Notebook - Examen Parcial 2 - Analisis de Datos - Julio Ruiz - 1284719"
output: html_notebook
---

```{r}
#aplico las librerias necesarias para hacer mi analisis
library(useful)
library(ggplot2)
library(dplyr)

```

```{r}
#en este espacio lo que hago es leer y explorar los datos que me brindan el dataset
dataset <- read.csv("Mall_Customers.csv")
dataset
# aca aplico lo de Genere la estadística General de los datos. (se recomienda usar la funcion summary 
summary(dataset)

```
```{r}
# aca elimino la columna CustomerID segun  la limpieza de los datos según lo visto en las secciones de feature engineering en clase.
datasetmod <- subset(dataset, select = -CustomerID)

# aca realizo la conversion de la columna Genre a codificacion binaria 1 hombre y 0 para mujer 
datasetmod$Genre <- if_else(datasetmod$Genre == "Male", 1, 0)
datasetmod
```

```{r}
# aca realizo para verificar si hay valores nulos
sum(is.na(datasetmod))
```

```{r}
#aca empiezo a entrenar el algoritmo de k-means
datatrain <- kmeans(datasetmod, centers = 5)
datatrain

```
```{r}
#aca empiezo a hacer el diagrama con centros
plot(datatrain, data = datasetmod)

```

```{r}
#aca realizo lo de aplicar la regla del codo 
df <- data.frame(matrix(ncol = 2, nrow = 0))
colnames(df) <- c("K", "error")
for (i in 2:25) {
  datatrain <- kmeans(x = datasetmod, centers = i)
  df[i-1,] <- c(i, datatrain$tot.withinss)
}
df

```

```{r}
#en esta seccion realizo la grafica de la regla del codo
#Determinar por medio del metodo del codo (elbow method) la cantidad de clusters optima para efectuar la segmentacion. (presente grafica con sus conclusiones de la cantidad de segmentos)
ggplot(data = df, aes(x = K, y = error)) +
  geom_line(linetype = "dashed") +
  geom_point()


```

```{r}
#y finalmente procedo a transformar la columna annual_income
datasetmod2 <- datasetmod
datasetmod2$Annual_Income_k <- (datasetmod2$Annual_Income_k - mean(datasetmod2$Annual_Income_k)) / sd(datasetmod2$Annual_Income_k)
datasetmod2

```

```{r}
#aca vuelvo a repetir los pasos anteriores 
datatrain2 <- kmeans(datasetmod, centers = 5)
datatrain2
```
```{r}
#el diagrama de centros
plot(datatrain2, data = datasetmod)
```

```{r}
#aca aplico nuevamente la regla del codo
df2 <- data.frame(matrix(ncol = 2, nrow = 0))
colnames(df2) <- c("K", "error")
for (i in 2:25) {
  datatrain2 <- kmeans(x = datasetmod2, centers = i)
  df2[i-1,] <- c(i, datatrain2$tot.withinss)
}
df2
```

```{r}
#grafico la regla del codo con mi annual_income ya modificado
ggplot(data = df2, aes(x = K, y = error)) +
  geom_line(linetype = "dashed") +
  geom_point()
```

```{r}
k_optimo <- 5 #K óptimo que identifico en la gráfica del codo
datatrain_optimo <- kmeans(datasetmod2, centers = k_optimo)
datatrain_optimo

```

```{r}
plot(datasetmod2[, c("Annual_Income_k", "Spending_Score")], col = datatrain_optimo$cluster, 
     main = "Segmentación de clientes con K óptimo", xlab = "Annual Income (Normalizado)", ylab = "Spending Score")
points(datatrain_optimo$centers[, c("Annual_Income_k", "Spending_Score")], col = 1:k_optimo, pch = 8, cex = 2)

```

